### ISSUE TITLE
Issue compiling for TronXY X5SA-Pro

### ISSUE THREAD

**Issue by orangeworx** [rhapsodyv/Marlin#29]
Hello everyone!
I've followed the README.MD for the X5SA but for the X5SA-Pro. I've managed to go through all the issues that presented as I was moving forward.
But there's on that's got me scratching my head. The #define TFT_LVGL_UI option seems to fail at compiling. I've "seen" a couple of working setups; a couple of posts talking about issues with the LVGL but after successful compilation, a youtube video where the OP is showing the functioning screen/GUI so I must be missing something.

### Description

When trying to compile with #define TFT_LVGL_UI (using VS Code), the terminal output is attached as a text file.
[error log.txt](https://github.com/rhapsodyv/Marlin/files/6183773/error.log.txt)

### Steps to Reproduce

1- Test build with Marlin 2.0 bug fix (latest) and standard config files
2- Swapping configuration.h and configuations_adv.h with the examples>TronXY>X5SA
3- Modifications following the README.MD file from X5SA examples folder.
4- Enablin TFT_LVGL_UI
5- Compiling

**Expected behavior:** Successful compilation
**Actual behavior:** Failure to compile - #error xxxx requires a programmable LCD controler.

Included config files (with #define TFT_LVGL_UI enabled)
[config.zip](https://github.com/rhapsodyv/Marlin/files/6183745/config.zip)

**Comment by orangeworx** [comment]
So I've had a chance to test a couple of things out and managed to get a build to succeed albeit minus a couple of features...
Bizarrely, every time I ran the build with `#define FILAMENT_RUNOUT_SENSOR` or `#define ADVANCED_PAUSE_FEATURE` uncommented, it failed.

So with `#define TFT_LVGL_UI enabled` uncommented, here are my results;
(for easier reading, I will say enabled for uncommented, disabled for commented.)
1- Compiles only if both are enabled.
2- Fails when ADVANCED_PAUSE_FEATURE is enabled, FILAMENT_RUNOUT_SENSOR is disabled
VSCode Terminal shows a repeat of the following error
SanityCheck.h:872:6: error: #error "ADVANCED_PAUSE_FEATURE requires a supported LCD controller (or EMERGENCY_PARSER)." (**in red text**) 
     #error "ADVANCED_PAUSE_FEATURE requires a supported LCD controller (or EMERGENCY_PARSER)."(**in yellow text**)
Enabling EMERGENCY_PARSER, also fails (seems to be another issue altogether, something about pause_menu_response). I've attached the logs for that separately
[EP1APF1FRS1.log](https://github.com/rhapsodyv/Marlin/files/6224030/EP1APF1FRS1.log)
3- Fails if FILAMENT_RUNOUT_SENSOR is enabled **and** ADVANCED_PAUSE_FEATURE disabled
VSCode Terminal shows a repeat of the following error
SanityCheck.h:863:5: error: static assertion failed: ADVANCED_PAUSE_FEATURE is required to use M600 with FILAMENT_RUNOUT_SENSOR. (**in red text**) 
     static_assert(nullptr == strstr(FILAMENT_RUNOUT_SCRIPT, "M600"), "ADVANCED_PAUSE_FEATURE is required to use M600 with FILAMENT_RUNOUT_SENSOR."); (**in yellow text**)

Hope this sheds some light. If anyone has any ideas, I don't mind testing.

**Comment by orangeworx** [comment]
@rhapsodyv I'm tagging you as I'm not sure what else to do. Tried posting this to marlin but apparently this was closed as a non-bug, user-support question. I don't use fb nor the reprap forums so I'm back here.

Worst yet (though not linked) I redownloaded the latest 2.0bf and I can't even compile a known working config, something to do with the new sanity checks
